services:
  - name: melita-bakes
    type: web
    env: production
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist
    envVars:
      - key: VITE_SUPABASE_URL
        value: your-supabase-url
      - key: VITE_SUPABASE_ANON_KEY
        value: your-supabase-key
      - key: ADMIN_EMAIL
        value: admin@example.com
      - key: ADMIN_PASSWORD
        value: securepassword123
